FILES:= main.c 0-rest_to_98.c 1-swap.c 2-strlen.c 3-puts.c 4-print_rev.c 5-rev_string.c 6-puts2.c 7-puts_half.c 8-print_array.c 9-strcpy.c
FLAGS:= -Wall -Wextra -Werror


all: $(FILES)
	@gcc $(FLAGS) $(FILES)
clean:
	@rm a.out
